apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - backend
  - frontend

# All generated resources are assigned to the study-app namespace unless they specify one explicitly.
namespace: study-app

# Useful for environment-based deployments (e.g., dev/staging/prod). This adds dev- to the names of resources.
namePrefix: dev-

# Patch: updates images by name across all resources. image: backend:latest Kustomize will turn it into image: backend:dev
images:
  - name: backend
    newTag: dev
  - name: frontend
    newTag: dev
